[build]
  base = "online-shop"
  command = "npm run build"
  publish = ".netlify/output" # NOT .next
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"